### PR TITLE
Add Oauth config from the oauth interface

### PR DESCRIPTION
**Pull request by gtato**
This PR adds an sasl/oauthbearer listener to the Kafka (based on the Strimzi implementation).
This listener is added as a response to kafka beying related to hydra (or oauth-external-idp-integrator)

### CODE REVIEW

**Comment by gtato** [comment]
@deusebio, @marcoppenheimer, @zmraul 
This is equivalent to the [PR on the VM](https://github.com/canonical/kafka-operator/pull/168). If you have comments that apply to both, I would rather you commented on the VM PR. I will port them here, once discussions are resolved there.

**Comment by deusebio** [comment]
@gtato I've been fixing the failure that you see in [this PR](https://github.com/canonical/kafka-k8s-operator/pull/112). 

Once that lands, I will just kindly ask you to rebase, such that we have a green pipeline

**Comment by deusebio** [comment]
@gtato we have just landed a small PR to avoid the failing tests of sync_docs and security tests. Just rebase and I believe all tests should be green! Thanks!

**Review by deusebio — APPROVED** [review]
Thanks @gtato !

**Review by zmraul — APPROVED** [review]

**Review by marcoppenheimer — APPROVED** [review]

**Pull request merged**
